language: ruby
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
- 2.5.0
- ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_script:
- export COVERAGE=true
script:
- bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: Wz6kbQXUl1J+XVLR/yt0XeI+FEiwcSNsGTsRdKBYSN1CEWnws0BwbWSN1tyRGmMXODiCAHchdGKEqgkm2Nk1/wEhBpCoF/clEeUq8fKyAIdKkEg3laBFI5dSdBm+eYcqQAdUnWeDHnQgdGT1lQBAe6tIAaN6Oqaw1v9bexvQgv8=
matrix:
  allow_failures:
  - rvm: ruby-head
sudo: false
