language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_install:
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
script:
  - RUBYOPT=$RSPEC_RUBYOPT bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: Wz6kbQXUl1J+XVLR/yt0XeI+FEiwcSNsGTsRdKBYSN1CEWnws0BwbWSN1tyRGmMXODiCAHchdGKEqgkm2Nk1/wEhBpCoF/clEeUq8fKyAIdKkEg3laBFI5dSdBm+eYcqQAdUnWeDHnQgdGT1lQBAe6tIAaN6Oqaw1v9bexvQgv8=
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RSPEC_RUBYOPT="--jit"
    - rvm: ruby-head
      env: RSPEC_RUBYOPT="--jit"   
sudo: false
